#include "consts.hpp"

const std::string HelpString = 
	"Arithmetic Operators:\n"
	"  +          Add\n"
	"  -          Subtract\n"
	"  *          Multiply\n"
	"  /          Divide\n"
	"  cla        Clear the stack and variables\n"
	"  clr        Clear the stack\n"
	"  clv        Clear the variables\n"
	"  !          Boolean NOT\n"
	"  !=         Not equal to\n"
	"  %          Modulus\n"
	"  ++         Increment\n"
	"  --         Decrement\n\n"

	"Bitwise Operators:\n"
	"  &          Bitwise AND\n"
	"  |          Bitwise OR\n"
	"  ^          Bitwise XOR\n"
	"  ~          Bitwise NOT\n"
	"  <<         Bitwise shift left\n"
	"  >>         Bitwise shift right\n\n"

	"Boolean Operators:\n"
	"  &&         Boolean AND\n"
	"  ||         Boolean OR\n"
	"  ^^         Boolean XOR\n\n"

	"Comparison Operators:\n"
	"  <          Less than\n"
	"  <=         Less than or equal to\n"
	"  ==         Equal to\n"
	"  >          Greater than\n"
	"  >=         Greater than or equal to\n\n"

	"Trigonometric Functions:\n"
	"  acos       Arc Cosine\n"
	"  asin       Arc Sine\n"
	"  atan       Arc Tangent\n"
	"  cos        Cosine\n"
	"  cosh       Hyperbolic Cosine\n"
	"  sin        Sine\n"
	"  sinh       Hyperbolic Sine\n"
	"  tanh       Hyperbolic tangent\n\n"

	"Numeric Utilities:\n"
	"  ceil       Ceiling\n"
	"  floor      Floor\n"
	"  round      Round\n"
	"  ip         Integer part\n"
	"  fp         Floating part\n"
	"  sign       Push -1, 0, or 0 depending on the sign\n"
	"  abs        Absolute value\n"
	"  max        Max\n"
	"  min        Min\n\n"

	"Display Modes:\n"
	"  hex        Switch display mode to hexadecimal\n"
	"  dec        Switch display mode to decimal (default)\n"
	"  bin        Switch display mode to binary\n"
	"  oct        Switch display mode to octal\n\n"

	"Constants:\n"
	"  e          Push e\n"
	"  pi         Push Pi\n"
	"  rand       Generate a random number\n\n"

	"Mathematic Functions:\n"
	"  exp        Exponentiation\n"
	"  fact       Factorial\n"
	"  sqrt       Square Root\n"
	"  ln         Natural Logarithm\n"
	"  log        Logarithm\n"
	"  pow        Raise a number to a power\n\n"

	"Stack Manipulation:\n"
	"  pick       Pick the -n'th item from the stack\n"
	"  repeat     Repeat an operation n times, e.g. '3 repeat +'\n"
	"  drop       Drops the top item from the stack\n"
	"  dropn      Drops n items from the stack\n"
	"  dup        Duplicates the top stack item\n"
	"  dupn       Duplicates the top n stack items in order\n"
	"  roll       Roll the stack upwards by n\n"
	"  rolld      Roll the stack downwards by n\n"
	"  stack      Toggles stack display from horizontal to vertical\n"
	"  swap       Swap the top 2 stack items\n\n"

	"Macros and Variables:\n"
	"  macro      Defines a macro, e.g. 'macro kib 1024 *'\n"
	"  macro      show macros (with no args)\n"
	"  x=         Assigns a variable, e.g. '1024 x=''\n\n"

	"Other:\n"
	"  help       Print the help message\n"
	"  prec       Set precision\n"
	"  exit       Exit the calculator\n\n"
	;


	/// press any key ... large output

